default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        exclude: /migrations/*

  - repo: https://github.com/prettier/prettier
    rev: "2.5.0"
    hooks:
      - id: prettier
        name: prettier-js
        entry: npx prettier --write '**/*.{js,jsx,ts,tsx,json,css,scss,less,html}'
        language: system



  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        args: [--max-line-length=100]
        exclude: (/__init__\.py$|/migrations/*)


  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort except __init__.py
        exclude: (/__init__\.py$|/migrations/*)

  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0
    hooks:
      - id: check-untracked-migrations


