language: python
python:
  - "3.11"

services:
  - docker

before_install:
  - docker-compose up -d --build
  - docker-compose exec backend python manage.py migrate

install:
  - docker-compose exec backend pip install -r requirements.txt

script:
  - docker-compose exec backend python manage.py test

after_script:
  - docker-compose down
